# Example Site settings
title: 'Game House'
url: 'https://ehei1.github.io'
#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
style: hacker
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console